version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
# docker compose run --service-ports web bash
  # go run cmd/main.go -b 0.0.0.0 &&

    command: >
      sh -c "go get github.com/gofiber/fiber/v2 &&
             go mod tidy &&
             go run cmd/main.go -b 0.0.0.0"