version: '3.8'

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
# docker compose run --service-ports web bash
  # go run cmd/main.go -b 0.0.0.0 &&
    command: >
      sh -c "go get github.com/gofiber/fiber/v2 &&
             go get gorm.io/gorm &&
             go get gorm.io/driver/postgres &&
             go get github.com/joho/godotenv &&
             go get github.com/rs/zerolog &&
             go mod tidy &&
             air ./cmd/main.go -b 0.0.0.0"
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
